name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.10
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
